name: SaesPvP
version: 1.3.1
main: com.saesdev.saespvp.SaesPvP
commands:
   ninja:
      description: Use the Ninja kit!
      usage: /<command>
   archer:
      description: Use the Archer kit!
      usage: /<command>
   default:
      description: Use the Default kit!
      usage: /<command>
   reset:
      description: Reset someone's kits.
      usage: /<command> [player]
   heavy:
      description: Use the Heavy kit!
      usage: /<command>
   pyro:
      description: Use the Pyro kit!
      usage: /<command>